### ISSUE TITLE
Which type of new framework/ language you expect to come in future?

### ISSUE THREAD

**Issue by nnitish** [Brocco/ama#2]
As you are a part of the world-leading company with a great knowledge and experience. So what you think about new framework/ language should come?

**Comment by Brocco** [comment]
I think we're in the middle of a framework/language explosion. I think JavaScript is the clear winner in the client-side space so that language is pretty much set. But what has really taken off recently are languages/add-ons that produce JavaScript (and WASM) to give developers better tooling when writing web applications.

As for frameworks, I think that there's too much of the "versus mindset" going on. The notion that if you like one framework then it's not OK to like or respect others is ridiculous and does nothing to move the web platform forward. That being said, while man people have taken that approach many of the contributors are actually communicating and collaborating about how to make things better by sharing ideas and approaches.

I hope this answers what you were looking for, thanks for asking!
